### ISSUE TITLE
Using fluent-plugin-mysql-replicator in the table without primary key

### ISSUE THREAD

**Issue by shigemk2** [y-ken/fluent-plugin-mysql-replicator#19]
I want to use this plugin with MySQL slow_log table(the setting `log_output` is TABLE).

But fluent-plugin-mysql-replicator requires primary key and slow_log table does not have primary key.

I want to use fluent-plugin-mysql-replicator with the table without primary key. Can I fix this plugin to enable to use the table without primary key? Or could you tell me how to use this plugin with slow_log table?

**Comment by y-ken** [comment]
Please try this plugin for that use-case
https://github.com/y-ken/fluent-plugin-mysql-query
