### ISSUE TITLE
"Too many connections" occurs in mysql_replicator_multi

### ISSUE THREAD

**Issue by Y-Asahi-dev** [y-ken/fluent-plugin-mysql-replicator#30]
I am using mysql_replicator_multi.
It seems that active connections are generated one after another by loop processing, and as a result, a “Too many connections” error occurs on the DB side.
Cause is
fluent-plugin-mysql-replicator / blob / master / lib / fluent / plugin / in_mysql_replicator_multi.rb
It seems that nest_db is not closed properly.

**Comment by cosmo0920** [comment]
Yep. `nest_db` instance is not closed properly.
I've created a patch to fix this issue: #31.
Could you check it?

**Comment by Y-Asahi-dev** [comment]
Thank you for your prompt reply.

**Comment by Y-Asahi-dev** [comment]
Sorry.
>I've created a patch to fix this issue: #31.
Can you backport this same support to v0.6.1?

**Comment by cosmo0920** [comment]
Sure. Will do.

BTW, did you read this article? https://www.fluentd.org/blog/drop-schedule-announcement-in-2019

We will stop Fluentd v0.12 development end of this year.
We recommend to migrate Fluentd v1 from Fluentd v0.12.

**Comment by Y-Asahi-dev** [comment]
Thank you.

>We will stop Fluentd v0.12 development end of this year.

Migration is not possible immediately, so we are considering migration as a future roadmap.

**Comment by cosmo0920** [comment]
I've released the backport patch as v0.6.2.

**Comment by Y-Asahi-dev** [comment]
I confirmed the fix in v0.6.2.
Thank you!

**Comment by y-ken** [comment]
Thank you for reporting and fixing 🙇
